inhabitedtype/httpaf

- lib/reqd.ml
> requires-output: fix requires_output computation for streaming case

- lib/parse.ml
- lib_test/test_httpaf.ml
This, along with the preceding pull requests, fixes the tests for the post-refactor API.
Closes #5
> fix failing tests

- examples/async_echo_post.ml
- examples/async_get.ml
- examples/async_post.ml
Update async examples to compile with the latest release.
> Update Async examples

- httpaf-async.opam
- httpaf.opam
- lib/parse.ml
Will be included in angstrom.0.9.0.
> angstrom-api: update parser for new angstrom API

- async/httpaf_async.ml
- examples/async_echo_post.ml
- examples/async_get.ml
- examples/async_post.ml
Replace Async v0.11.0 deprecated apis.
> Replace deprecated API.

- lib_test/test_httpaf_server.ml
This test exposes an issue where a response hangs indefinitely because
`respond_with_streaming` puts the writer into `yield` mode so that it
doesn't write until the first `flush`, but if the first `flush` call
happens before the write loop "exhausts" the yield, it will just get
stuck.
This requires a change in Faraday to fix: https://github.com/inhabitedtype/faraday/pull/44
> add a test for flushing streaming bodies synchronously

- lib/httpaf.mli
See https://github.com/ocaml-community/utop/pull/269
cc @avsm I think I'm doing this right?
> Install toplevel printers automatically in modern utop

- benchmarks/wrk_async_benchmark.ml
- examples/async/async_echo_post.ml
- examples/async/async_get.ml
- examples/async/async_post.ml
relates to #113
Signed-off-by: Anurag Soni <anurag@sonianurag.com>
> Port async examples to Command.Param

- httpaf.opam
Make sure that inhabitedtype/faraday#44 included.
> faraday-constraint: increase lower bound to pickup bugfix

- lib/httpaf.mli
also other misc tweaks to the interface file documentation.
> httpaf.mli: fix doc comment for `Body.schedule_read`

- examples/async/async_get.ml
- examples/async/async_post.ml
- examples/lwt/lwt_post.ml
Signed-off-by: Anurag Soni <anurag@sonianurag.com>
> Update examples to use same arguments

- examples/async/async_echo_post.ml
- examples/lwt/lwt_echo_post.ml
This is a very minor, self-explanatory contribution.
Thanks for your hard work @seliopou!
> Print port in example output

- lib/headers.ml
When compiling to JS (via js_of_ocaml) local exceptions used for control flow are getting very expensive (V8 at least). This PR tries to alleviate some of the places, where functions with local exceptions appeared in the top of Node.js profile.
See [#835 in js_of_ocaml repo](https://github.com/ocsigen/js_of_ocaml/issues/835).
> Tail-recursive equal implementation

- lib/headers.ml
Combined with the inlining of of the `lower` function, this has the advantage of not using any stack. Replacing `lower` with a branch-free, case-insensitive equality check would further improve things.
> header-equal-loop: implement the equals check using a loop

- lib/body.ml
- lib_test/test_httpaf.ml
Similar fix to #145, but adds a test to confirm the fix and lifts the branch up higher to avoid additional work.
Closes #144.
> Only transfer to the writer if there is something to transfer

- lib/headers.ml
- lib_test/test_httpaf.ml
> Fix bug in Headers.replace

- lib_test/test_httpaf.ml
Exercise some basic valid and invalid inputs.
> test-request-parser: add tests for the request parser

- lib/headers.ml
- lib_test/test_httpaf.ml
I also added a test that would have caught this regression.
> Fix replacing non-trailing headers

- lib/reqd.ml
Similar to recent changes that added `Input_state.t`, this adds an
`Output_state.t` with an additional `Waiting` state, as, unlike input
data, the output may be waiting for a request handler to decide how or
what to write to the body. Even though we changed `requires_output` to
return an output state instead, this function was no longer used in
`Server_connection` after the recent changes moving the write loop
continuation directly to the writer. So this change is fairly trivial,
but it is a necessary step in supporting upgrade requests as we do
additional refactoring of the server and its request queue handling
semantics.
This also seemed like a good opportunity to rename `Complete`, since it
is really a dual to `Streaming`, and the name felt a little misleading
(and in fact has tripped …
> add output state variant to reqd

- lib/headers.ml
- lib_test/test_headers.ml
This definitely needs exhaustive testing before it's merged.
> Use branch free, case-insensitive comparison for headers

- lib/body.ml
- lib/httpaf.mli
- lib/message.ml
- lib/parse.ml
- lib/status.ml
Feel free to edit or close, it's up to you
> add some miscellaneous comments from a long-term branch

- lib/client_connection.ml
- lib_test/test_client_connection.ml
Using Client_connection with a streaming body has a bug whereby it will close the writer before sending the final chunk. This patch fixes the issue.
There is a test which now passes but fails if the change to lib/client_connection.ml is reverted.
> Fix client closing writer too soon

- httpaf-lwt-unix.opam
From https://github.com/ocaml/opam-repository/pull/18864
> add missing lwt constraint

- lib_test/test_server_connection.ml
I realized a recent branch that added the `is_errored` boolean actually
didn't have a test that showed when it is used. It came with a test, but
that test actually passed regardless. This is because there are two ways
to invoke `set_error_and_handle`: either the runtime uses `report_exn`,
or the parser enters an error state and the read loop discovers that.
The latter always means that `next_read_action` does *not* shut down the
writer, which is evident because `set_error_and_handle` is followed by a
`Close` return.
A test was added for the former. Along the way I thought of a few extra
scenarios to test, including one that might be new -- the
`error_handler` must be used to complete a request if invoked, or the
state machine will hang. I didn't port these onto the master from a week
ago …
> improve error test coverage
