inhabitedtype/httpaf

lib/response.ml
If the default callback is the active one, then it can be overridden. Exactly the opposite behavior of the previous version of the code.
Related to #5
=> response-ready: invert check for installed callback

lib/reqd.ml, lib/serialize.ml
This is code that was overlooked in the refactoring that immediately preceded public release. It behaves correctly, though it should be cleaned up in the future, as described in the inline comment.
Related to #5.
=> flush response body

lib/parse.ml
It was unclear when and where the buffer read/write window was being updated, which caused assertion errors in the code after the last refactoring. This commit makes it clear that `report_read_result` is responsible for zeroing out the "committed" byte count in the parser state, and shifting the read/write window of the input buffer accordingly.
=> parser invariant

httpaf-async.opam, httpaf.opam, lib/httpaf.mli, lib/iOVec.ml, lib/parse.ml, lib/reqd.ml, lib/request.ml, lib/response.ml, lib/serialize.ml, lib_test/test_httpaf.ml
There is one performance regression that's been introduced. This will require a new, low-level parser in Angstrom in order to avoid some copies.
Regression caused by inhabitedtype/angstrom#97, may be resolved in part by inhabitedtype/angstrom#99.
=> upgrade-af: conform to new angstrom/faraday interfaces

async/httpaf_async.ml, lib/connection.ml, lib/httpaf.mli
Making it a labeled argument along with a bunch of optional arguments requires the user to provide _all_ arguments, even if they're optional.
=> conn-create: make request handler a non-labeled argument

.travis.yml, async/jbuild, lib/jbuild
Add 4.06.0 to the build matrix.
=> safe-string compatibility

META.httpaf.template
There hasn't been an official release of httpaf yet, so the deprecation warning is not needed.
=> rm-META: remove unneeded META file

lib/connection.ml, lib/serialize.ml
Just query the encoder to determine whether the writer is closed.
=> simplify-serializer: The closed field was redundant

examples/async_echo_post.ml, examples/jbuild, lib/httpaf.mli, lib/parse.ml, lib/request.ml, lib_test/test_httpaf.ml
The parser did not close request bodes that had a fixed-length encoding. This pull request fixes that problem. Unfortunately that exposed a problem in the buffering logic for request input. So for the time being httpaf can't be used to buffer input as a result of partial reads. Hopefully this will be fixed in the future.
Closes #19.
@sgrove can you confirm the fix?
=> Deliver EOF for request bodies

lib/httpaf.mli
`Response.body_length` could not return `Bad_request`.
=> fix type of Response.body_length

lib/connection.ml, lib/httpaf.mli, lib_test/test_httpaf.ml
Replace it with `is_closed`. In addition, document some useful functions and remove the unnecessary `shutdown_input` function.
=> server-rm-state: remove state function from server connection

lib/version.ml
Return the major version comparison result when it is _not_ equal to zero, and otherwise return the minor version comparison result.
=> fix-version-compare: fix major version comparison

lib/iOVec.ml
shiftv should continue to loop when the current iovec is shorter than the amount that should be shifted. The code was doing the opposite before this change.
=> fix-shiftv: bounds check was reversed

lib/httpaf.mli, lib/reqd.ml
It was never fully implemented to begin with so just remove the code.
=> remove-switch: switching protocols not supported in this way

lib/httpaf.mli, lib/iOVec.ml, lib_test/test_httpaf.ml
Pull request #33 purported to fix a bug, and did identify the presence of a bug, but did not completely address it. It was not sufficient to swap the comparison, but also modify the false branch to only shift off `n` from the iovec at the head of the list, rather than the length of the iovec itself.
This pull request adds tests demonstrating the bug, fixes the bug, and also fixes a misleading error message that came up while testing.
=> Fix IOVec.shiftv (again)

lib/body.ml, lib/client_connection.ml, lib/httpaf.mli, lib/parse.ml, lib/reqd.ml, lib/server_connection.ml, lib_test/simulator.ml, lib_test/test_httpaf_client.ml, lib_test/test_httpaf_server.ml
The parser failed to properly parse multiple chunks in a chunked encoding. This was due to a few different problems with the parser, which was ultimately a result of bad testing input in the test simulator. The bugs on the parsing side were:
* chunked request bodies were being closed prematurely by the `fixed` parser;
* the `CRLF` at the end of each chunk was not being consumed; and
* the parser was (incorrectly) expecting a `CRLF` after the final chunk.
There was a corresponding serialization side, in which chunked bodies were not emitting the final `0\r\n` chunk.
This pull request all of these bugs at once, as they're somewhat interrelated. See commit messages for a bit more detail.
=> Fix chunked encoding

async/httpaf_async.ml, benchmarks/wrk_async_benchmark.ml, lib/client_connection.ml, lib/httpaf.mli, lib/parse.ml, lib/server_connection.ml, lib_test/simulator.ml
With the latest release of angstrom it's possible to implement a zero-copy read interface in httpaf, so that's what this pull request does.
Previously `next_read_operation` would indicate that more input was needed by returning a  `Read` variant, which would also contain a `Bigstring.t`. The caller would then have to blit any available input into that `Bigstring.t` and then report the read result by calling `report_read_result`.
The new interface simply returns a `Read` that has no additional arguments. This indicates that the caller should call `read` with the `Bigstring.t` containing the new input at a given offset and for the length specified, thus avoiding the copy that was necessary in the previous interface. If instead the caller has no further input (for example, because the input …
=> Zero-copy read API

lib/body.ml
When you yield a writer, the callback is either stored in one of three
places, or it is invoked immediately by `Body.when_ready_to_write`. The
immediate invocation happens if the body is closed, but that conditional
does not prevent the rest of the function from running. In some cases,
you may immediately invoke a callback, store it in
`t.when_ready_to_write`, and then later invoke it again later when that
field is checked.
This also moves the check for `t.when_ready_to_write` before the
synchronous invocation. In the case where we have a pending callback, it
would be nice for the two possible outcomes of `when_ready_to_write` to
behave similarly.
=> fix double callback in when_ready_to_write

lib/reqd.ml, lib/serialize.ml, lib/server_connection.ml
Due to a complicated chain of if/then/else expressions, the
`advance_request_queue_if_necessary` function was structured in such a
way that the branch to handle requests ending a persistent connection
was actually being applied to non-complete requests.
This fix exposed a bug in the tests where the `connection: close` header
would cause the request to be closed immediately. This was because
`Reqd.is_complete` is true as long as there is nothing to be read or
written -- that is, the request body is complete and the entire response
body has made it to `t.writer` but _not necessarily flushed_. Combine
this with the fact that the proceeding `shutdown` would close the
writer, causing it to be drained of pending writes, and you have
connections that close immediately.
We fix this by changing …
=> fix advancing request queue

httpaf.opam
This fixes OPAM's warning 47:
```
[WARNING] Failed checks in opam file from upstream of httpaf:
warning 47: Synopsis should start with a capital and not end with a dot
```
=> Minor fix: Synopsis should start with a capital and not end with a dot

lib/httpaf.mli, lib/reqd.ml, lib_test/test_httpaf_server.ml
This is related to #65. I managed to get websockets working using
Conduit in order to gain access to the file descriptors. However,
because streaming responses wait for the first write to flush response
bodies, I could never deliver the connection upgrade with 1. an empty
response body and 2. while not closing the writer.
Making `wait_for_first_flush` configurable (which I see was already in
the roadmap) solves this problem.
I've tested this in my code and it's working really well now. Please
let me know if you had thought of another way of configuring this
behavior.
=> Make `wait_for_first_flush` configurable in streaming responses

async/httpaf_async.ml, async/httpaf_async.mli, lib/client_connection.ml, lib/config.ml, lib/httpaf.ml, lib/httpaf.mli, lib/server_connection.ml, lwt/httpaf_lwt.ml, lwt/httpaf_lwt.mli
This refs #18 in that users can now set the buffer size they want. It
also gets rid of a pending `TODO` in the code.
=> Make read buffer size configurable again

async/httpaf_async.mli, lib/httpaf.mli, lib/reqd.ml, lib/server_connection.ml, lwt/httpaf_lwt.ml, lwt/httpaf_lwt.mli
The handle parameter of a server connection was originally intended to support upgrades within the HTTP state machine. This approach was never actually tested for feasiblity. In the mean time a different approach of building support for upgrading into the runtime has been tested for feasiblity, and will be adopted instead.
=> remove-handle-type-param: approach has been abandoned

Makefile, examples/async/async_echo_post.ml, examples/async/dune, examples/lwt/dune
This adds a new `examples` target to build the dune alias `@examples`
which is defined in the individual `dune` for each example directory.
=> add examples make target

Makefile
When I changed this from `jbuilder` to `dune`, I didn't try it and
forgot to remove the `--dev` flag.
=> fix examples rule

async/httpaf_async.ml, lwt/httpaf_lwt.ml
This is related to #77 and #78, but independent enough to warrant a new
pull request.
When using http/af over HTTPS, the SSL / TLS library needs to keep the
socket open for writing because there might be writes on the upgraded
connection.
This changeset proposes that the http/af `Client` modules don't close
the socket for sending, and instead wait until the request is over to
shutdown the file descriptor.
=> Client bindings: don't shutdown_send immediately

lib_test/test_httpaf.ml
Demonstrate executions for request handlers that raise synchronously and
asynchronously, as well as handle the error by generating an error
response both syncrhonously and asynchronously.
Asked for in #74.
=> report-error-tests: test error reporting for all {,a}sync cases

lib/server_connection.ml
in `Server_connection`, `is_shutdown` and `is_closed` had the same implementation.
This patch removes `is_shutdown` and keeps `is_closed` since that's what is exposed in the `.mli`
=> cleanup: Remove `is_shutdown`

lib/serialize.ml, lib_test/test_httpaf.ml
When using transfer-encoding: chunked, each chunk that's sent over the
wire needs to be terminated with \r\n.
=> Fix response chunk encoding.

async/dune, httpaf-async.opam
=> Remove angstrom-async dependency from httpaf-async

lib/body.ml, lib/server_connection.ml, lib_test/test_httpaf.ml
This fixes up an old hack to get chunked responses to work properly, and which interacted poorly with streaming bodies that were not chunk encoded.
The code itself needs a once-over to make it a bit more obvious what's going, but that will be left for a subsequent PR.
Closes #126
=> Fix bug in asynchronous streaming body responses 

httpaf-lwt-unix.opam
Seems like right now the `httpaf-lwt-unix` package can't be pinned because of the name in the opam file.
This is a follow-up to https://github.com/inhabitedtype/httpaf/pull/124 which I think missed renaming the `name: ` field in the opam file
=> Fix opam package name for httpaf-lwt-unix

lib/client_connection.ml
=> rm-response-handler: don't store request handler in client state

lib/client_connection.ml, lib_test/test_httpaf.ml
`Client_connection.report_exn` was previously calling `shutdown` which assumed that if the connection was awaiting a response, then the error should always be assumed to be an eof. The code now checks each case and calls the error handler with the provided error after closing the connection.
=> Fix bug in Client_connection.report_exn

lib/serialize.ml, lib_test/test_httpaf.ml
When a write result of `Closed` is reported, the connection continues to report that there are bytes to write. At that point it should just discard any bytes it could write and report that no further writing is possible.
Closes #143.
=> Writer fix

lib/body.ml, lib/serialize.ml, lib_test/test_httpaf.ml
=> Fix empty chunk-encoded responses

httpaf-async.opam, httpaf-lwt-unix.opam, httpaf.opam
See ocaml/opam-repository#14266
=> dune-not-build: dune can't be a build dependency

lib/headers.ml, lib_test/test_httpaf.ml
A header field wouldn't be removed if it matched the needle and was preceded by non-matching fields in transmission order.
=> Fix bug in Headers.remove

lib/headers.ml
=> rm-deubg-printfs: remove debug output

lib/server_connection.ml, lib_test/test_httpaf.ml
Ensure that parser state is saved before attempting to send more (or no) input the `Parse` module.
Closes #152.
=> Fix read loop re-entrancy issue

lib/server_connection.ml
Cleanup wakeup callback bookkeeping that got a bit hairy as a result of #158. `Body` only allows a single wakeup callback to be registered with it, so just propagate that constraint up to the server connection layer.
=> wakeup-cleanup: only allow one wakeup calblack per I/O operation

lib/parse.ml, lib_test/test_httpaf.ml
Add tests for the response parser.
This revealed a bug in the status-code parser that would raise on certain invalid inputs. The fix is also included in this PR.
=> Test response parser

lib/parse.ml, lib_test/test_httpaf.ml
When the parser has been fed input but has not hit a commit point so the entire buffer can be consumed, a subsequent `report_exn` call will result in the parser raising with the message "input shrunk".
The fix is to not feed any input to the parser when it is force-closed, but instead make the next call to `next` report close. This will give the caller the opportunity to feed the parser the final bytes available (or to not) before everything shuts down.
=> Fix "input shrunk" bug

lib/body.ml, lib/optional_thunk.ml, lib/optional_thunk.mli, lib/reqd.ml, lib/server_connection.ml
Introduce an `Optional_thunk.t` type to replace most of the `Sys.opaque_identities` used throughout the code. This type requires one to check whether it is "none" or "some" before using it as a regular function. The `unchecked_value` function reminds you that you might be performing an unsafe operation.
=> Optional thunk

lib/body.ml, lib/optional_thunk.ml, lib/optional_thunk.mli, lib/reqd.ml, lib/server_connection.ml
Replace calls to to `Optional_thunk.unchecked_value f ()` with `Optional_think.call_if_some f`. Sounds safer, and if the none type ever changes representation no call sites need to change.
=> call-if-some: add Optional_thunk.call_if_some and use it

lib/reqd.ml
=> response-state: Put Reqd.response_state in its own module 

lib/reqd.ml, lib/server_connection.ml
Part of #172, but changed a constructor name.
=> input-state: use a type to indicate Reqd input state

lib/body.ml, lib_test/test_server_connection.ml
All of our streaming response tests wrote out their bodies synchronously
in the request handler, so here we add some tests that observe the write
loop yielding in between writes. In doing this, we expose a latent bug
regarding non-chunked, 0-byte streaming responses, which could get the
writer into a stuck state.
What was happening was we relied on `transfer_to_writer_with_encoding`
to pass the encoding along and flip the `write_final_if_chunked` to
`false`, but since we have no body, that bool never gets flipped and the
body thinks it is chunked. This is an issue because
`t.write_final_if_chunked` determines whether or not the body has
pending output, even though it might be a noop.
So roughly:
1. Body is closed by user
2. Body wakes up the writer
3. Writer tries to advance the request …
=> add async streaming tests and fix chunked bug

lib/headers.mli, lib/parse.ml, lib_test/test_client_connection.ml, lib_test/test_server_connection.ml
We recursively read off headers from requests (in the case of a server)
and responses (in the case of a client) and construct a list out of
them, but because `Headers.t` is an exposed type, we were able to pass
an ordered list when it should have been reversed. This change adds a
simple mli that matches the interface of `Httpaf.Headers`, which causes
a build error in one location in the parser where we need to reify the
headers from the alist we have. And since we use `lift2 cons`, we have
an ordered list. I also added a test that makes sure they are read in
the correct order, and fixed a test that seemed to be working around the
issue.
=> expose parsed headers in the order they were read

lib/body.ml, lib/client_connection.ml, lib/parse.ml, lib/reqd.ml, lib/serialize.ml, lib/server_connection.ml, lib_test/test_server_connection.ml
Previously we did this dance where whenever the writer is in a yielded
state, we start by holding on to it in the server connection and then
passing it off to the reqd when it's created. And then *that* was
sometimes handed off to the `Body` so that it could call it when the
user invoked `Body.flush` or `Body.close_and_drain`. And then each
further yield, we have to figure out who should be holding on to it. It
gets a little confusing and forces us to do some extra invariant checking.
Now we put the yield callback in neither place and instead keep it on
the writer directly. There is exactly one writer per server connection,
and it is also the place we ask for `next` once the writer is awake. So
it seems like a much more natural place to keep it.
We stil have to consider the body, though. …
=> move yield to writer

lib/server_connection.ml, lib_test/test_server_connection.ml
This was a regression from #178: since we incorrectly called this body a
reader, we did not wire up a callback so that it could wake the writer
when closed or flushed. Added a test that fails without the fix.
=> wake writer when reporting exn through the server

examples/async/async_get.ml, examples/async/async_post.ml, examples/lib/httpaf_examples.ml, examples/lwt/lwt_get.ml, examples/lwt/lwt_post.ml, lib/parse.ml, lib/server_connection.ml, lib_test/test_client_connection.ml, lib_test/test_server_connection.ml
Adds a test to demonstrate the broken nature of bad parses or bad requests, and then fixes it by wiring the error case through to the server connection.
@seliopou I know we talked about this briefly and had a few thoughts on what to do. In one situation, we would just forcibly close the connection on a parse error. This makes sense if you just connect to port 80 and write garbage, but it makes less sense if you write a well-formed request with a slight typo. I feel like we had a second idea too, but I forget what it was. I went with the approach of using the existing code, which calls out to the error handler.
=> Fix parse error cases

lib/server_connection.ml, lib_test/test_server_connection.ml
Fix issue #189 
If multiple requests were received in a single TCP frame and fit in one buffer, a non-empty read was still forced after the first request, making the server unresponsive to the following one until more data was received.
Only observed with the LWT backend, but seeing the code Ithink Async is affected too.
=> Fix unresponsiveness with multiple requests in a single buffer.

lib_test/helpers.ml, lib_test/test_server_connection.ml
This looks like a lot because it is. So here's the thing: when we write
tests like we have been, we just call `next_read_operation` and
`next_write_operation` whenever we want. However, that's not reflective
of reality -- under normal situations, those are called only as a result
of a read/write or when the loop is woken up. So we can easily write a
test that looks right, but never actually happens in the real world.
This approach is different. Abstract away the `Server_connection`, write
a make-shift read/write loop, and memoize the operations when you learn
about them. This way, instead of writing tests that assert against the
*next* operation, they can assert against the *current* operation -- the
one that the loop already discovered.
Additionally, we can make sure that we never send …
=> massively refactor server connection test framework

lib/parse.ml
The fact that this is unused means that there is no representation of a
close-delimited request body. If the content-length header is missing,
it's assumed to be 0 bytes fixed-length.
=> remove unused close-delimited match

lib_test/helpers.ml, lib_test/test_client_connection.ml, lib_test/test_server_connection.ml
This was an untested case that was exposed in another PR. We should be
able to respond before reading the body. Add some test helpers for
headers and replace usages for consistency. I added a currently-unused
`writer_ready` assertion because it's nice when you're trying to probe
the state to debug.
=> add test for responding mid-read

lib_test/test_server_connection.ml
This tests a specific situation where multiple requests are queued, but
the server wants to close the connection after the first.
=> add test for queue mechanics

lib/headers.ml, lib/headers.mli, lib/httpaf.mli, lib/request.ml, lib/response.ml, lib_test/test_request.ml, lib_test/test_response.ml
This does two main things to bring it in line with the spec:
1. The values are checked case-insensitive
2. If the header is specified multiple times, later values override
previous ones
Comprehensive test coverage was added.
=> add proper transfer-encoding parsing

lib/reqd.ml, lib/server_connection.ml
This is a prelude to #159 which introduces upgrade requests, with a few
major changes in `Server_connection`.
The goals here is to try to make queue management easier to reason about
by folding bits of logic from `advance_request_queue_if_necessary` into
`next_read_operation` and `next_write_operation` such that we only
perform side-effects when the operation in question demands it.
One of the ways I tried to make this easier to reason about was to make
the `next_<read|write>_operation` functions very parallel. Getting the
read operation starts out with a short-circuit for shutting down when
the server can no longer make progress (reader is closed and queue is
empty). This doesn't feel like it belongs here. Perhaps this check
should be part of `advance_request_queue` with some extra logic …
=> refactor request queue mechanics

lib/server_connection.ml, lib_test/test_server_connection.ml
When you shutdown the connection and we close the reader, a surprising
thing happens under certain conditions: the read loop wakes up, asks for
the next read operation, and is told to yield. It tries to yield, and
then the state machine raises -- you shouldn't be yielding if the
connection is closed!
The reason for this is our explicit return of [\`Yield] in
`_final_read_operation_for`. As mentioned in my lengthy comment, I think
the real issue here is that if we want to circumvent `Reader.next`, we
have to make sure we're not yielding when the reader cannot take any
more input anyway.
I thought of fixing this in a few ways, like adding explicit yielding
and continuing mechanisms to the reader at request boundaries, which is
something that has come up in the past as being a bit tricky to …
=> fix read loop with `shutdown`

lib/body.ml, lib_test/test_client_connection.ml, lib_test/test_server_connection.ml
If one calls `on_read` when data is immediately available, we should immediately schedule a read. For instance, consider the following sequence of events:
1. Data arrives on a connection
2. `Body.schedule_read` is called
3. A long time passes
4. More data arrives on the connection
In this case, the `on_read` function passed to `Body.schedule_read` was not being called until step (4).
This PR fixes the issue and presents a test using both `Client_connection` and `Server_connection`.
=> Body.schedule_read should call on_read immediately if data is available

Makefile
I use this for fast feedback while developing and thought it would be
good to put in the `Makefile`. I would have built the examples and
benchmarks too, but all the linking makes the whole iteration take an
order of magnitude longer. Maybe there's some dune option I'm missing
here to let us build but not link.
=> add `make watch` for development

lib/parse.ml, lib/server_connection.ml, lib_test/test_server_connection.ml
Currently, if there is a parse error after `read_eof`, the runtime has no
chance to discover it. The error is not surfaced immediately, and if
the runtime calls `next_read_operation`, it just gets `` `Close``.
This is because `Reader.next` first checks to see if it is closed, and
if so, always returns `` `Close``.
This feature fixes this by inverting the logic in that function.
Unfortunately this leads to another problem: the parser effectively
expects an unending stream of requests, because after finishing
parsing one request it immediately expects the next one. This means
that read_eof is guaranteed to lead to a parse error. Thankfully this
is easily fixed by treating an empty input as a valid as well.
=> Fix parse error at EOF

lib/server_connection.ml, lib_test/test_server_connection.ml
`Server_connection.shutdown` immediately calls `Writer.close`. But we should flush the response body in case the user has written something to the body and not yet flushed the body.
You could argue this is not needed because the user should be careful to flush their body before shutting down. In the structure of my program, this is hard to ensure. I expose a function to shut down the HTTP server, which calls Server_connection.shutdown on all live connections. It's hard for that function to know what the current state of all of the response handlers are.
=> Flush response before shutting down

httpaf.opam, lib/dune, lib/httpaf.mli, lib/reqd.ml
This was integrated into stdlib in 4.03, which is the earliest version we support. Fixes #221.
=> remove references to result package

lib/parse.ml, lib_test/test_server_connection.ml
finsh has side effects so ensure that the parser on the lhs of the sequence operator has consumed its input before calling it.
=> fix-zero-chunk-end-of-request: finish after eol consumed
